[server]
port = 8501
headless = true
enableCORS = false
maxUploadSize = 10

[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#f0f2f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#080f1e"
font = "sans serif"

[browser]
gatherUsageStats = false
